feat(helm chart): prepare helm chart for release 4.1.0
openebs/openebs pull request #3754
Opened 2024-07-05 11:44 UTC by Abhinandan-Purkait

### Changes
- Updates the dependent charts with their respective latest releases.
- Updates the relevant README

2024-07-05 11:48 UTC, niladrih requested changes
You'd have to add monitoring here
Instead of 'engines', you can put it under 'utils'?
WDYT @tiagolobocastro @avishnu @dsharma-dc @w3aman @Abhinandan-Purkait @abhilashshetty04 ?

2024-07-05 11:49 UTC, Abhinandan-Purkait commented
@w3aman Please add the monitoring in this PR.

2024-07-05 11:50 UTC, Abhinandan-Purkait commented
> You'd have to add monitoring here Instead of 'engines', you can put it under 'utils'? WDYT @tiagolobocastro @avishnu @dsharma-dc @w3aman @Abhinandan-Purkait @abhilashshetty04 ?

How about just monitoring?

2024-07-05 11:51 UTC, niladrih commented
@Abhinandan-Purkait please also incorporate my commit from https://github.com/openebs/openebs/pull/3747.

2024-07-05 11:51 UTC, niladrih commented
> > You'd have to add monitoring here Instead of 'engines', you can put it under 'utils'? WDYT @tiagolobocastro @avishnu @dsharma-dc @w3aman @Abhinandan-Purkait @abhilashshetty04 ?
> 
> How about just monitoring? In the values root.

Yep, works for me. `monitoring.enabled`.

2024-07-05 11:59 UTC, Abhinandan-Purkait commented
> @Abhinandan-Purkait please also incorporate my commit from #3747.

Done. Please check.

2024-07-05 12:21 UTC, niladrih approved these changes
LGTM!

2024-07-05 12:26 UTC, tiagolobocastro commented on charts/values.yaml
> +  etcd:
above on line 35, change to 2.7.0 ?

2024-07-05 14:48 UTC, Abhinandan-Purkait commented on charts/values.yaml
> +  etcd:
Done.

2024-07-05 15:06 UTC, tiagolobocastro approved these changes

2024-07-08 08:44 UTC, niladrih requested changes

2024-07-08 08:44 UTC, niladrih commented on charts/values.yaml
> +    enabled: false
```suggestion
```

2024-07-08 08:45 UTC, niladrih commented on charts/README.md
> +| monitoring.enabled | bool | `false` | Enable monitoring stack for openebs engines |
```suggestion
```

2024-07-08 08:54 UTC, niladrih approved these changes

2024-07-08 08:54 UTC, niladrih commented on charts/README.md
> +openebs openebs         1               2024-03-25 09:13:00.903321318 +0000 UTC deployed        openebs-4.1.0   4.1.0
```suggestion
openebs openebs         1               2024-07-07 09:13:00.903321318 +0000 UTC deployed        openebs-4.1.0   4.1.0
```

2024-07-08 09:41 UTC, Abhinandan-Purkait commented
> Please squash all of the commits, if possible.

Isn't squash and merge enough here?

2024-07-08 13:45 UTC, merged